language: node_js
node_js:
  - "10"
services:
  - docker
env:
  - DOCKER_IMAGE=gawesomebot
  - DOCKER_TAG=latest
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
install: npm ci
jobs:
  include:
    - stage: test
      script: bash ./travis/test.sh
    - stage: build
      if: type = push
      script: bash ./travis/build.sh
after_success:
  - wget https://raw.githubusercontent.com/KingDGrizzle/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - if [ "$TRAVIS_BRANCH" == "$DOCKER_BRANCH" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG .;
      docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG;
    fi
after_failure:
  - wget https://raw.githubusercontent.com/KingDGrizzle/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
dist: trusty
sudo: true
