version: "3"
services:

  db:
    image: mongo:${DB_VER}
    volumes:
      - mongodb:/data/db
    ports:
      - ${DB_PORT}:27017
    restart: always

  bot:
    depends_on:
      - db
    ports:
      - ${NODE_PORT}:80
    environment:
      - NODE_ENV=${NODE_ENV}

volumes:
  mongodb:
    external: true
